import { NavigationSchema } from '@loopdev/contracts';

/**
 * @file fixtures.ts
 * @description Configuraciones de navegación reales para pruebas e integración.
 */

export const MARKETING_STUDIO_SCHEMA: NavigationSchema = {
  version: '1.0',
  suite: {
    suiteId: 'marketingStudio',
    suiteName: 'Marketing Studio',
    suiteIcon: 'Megaphone',
    accentColor: 'var(--lpd-color-brand-primary)',
    surfaceVariant: 'canvas',
  },
  exitHatch: {
    label: 'Back to OS',
    icon: 'ArrowLeft',
    route: { routeId: '/launchpad' },
  },
  groups: [
    {
      id: 'operativo',
      label: 'Operaciones Core',
      priority: 10,
      collapsible: true,
      items: [
        {
          id: 'nav.overview',
          kind: 'module',
          label: 'Suite Dashboard',
          icon: 'LayoutDashboard',
          priority: 5,
          moduleId: 'overview',
          route: { routeId: '/marketing-studio' },
          tooltip: 'Resumen operativo de la suite',
        },
        {
          id: 'nav.brand-hub',
          kind: 'module',
          label: 'Brand Hub',
          icon: 'LibraryBig',
          priority: 10,
          moduleId: 'brand-hub',
          route: { routeId: '/marketing-studio/brands' },
          tooltip: 'Identidad y gobernanza de marca',
        },
        {
          id: 'nav.asset-manager',
          kind: 'module',
          label: 'Asset Manager',
          icon: 'FolderKanban',
          priority: 20,
          moduleId: 'asset-manager',
          route: { routeId: '/marketing-studio/dam' },
          tooltip: 'Gestión de activos digitales',
        },
        {
          id: 'nav.content-engine',
          kind: 'module',
          label: 'Content Engine',
          icon: 'Sparkles',
          priority: 30,
          moduleId: 'content-engine',
          route: { routeId: '/marketing-studio/content' },
          tooltip: 'Generación de contenido con IA',
        },
        {
          id: 'nav.campaign-orchestrator',
          kind: 'module',
          label: 'Campaign Orchestrator',
          icon: 'Workflow',
          priority: 40,
          moduleId: 'campaign-orchestrator',
          route: { routeId: '/marketing-studio/campaigns' },
          tooltip: 'Orquestación de campañas',
        },
      ],
    },
    {
      id: 'estrategia',
      label: 'Estrategia & IA',
      priority: 20,
      collapsible: true,
      items: [
        {
          id: 'nav.insights',
          kind: 'module',
          label: 'Insights & Intel',
          icon: 'BarChart3',
          priority: 10,
          moduleId: 'insights-intelligence',
          route: { routeId: '/marketing-studio/insights' },
          tooltip: 'Analítica y predicciones',
        },
        {
          id: 'nav.growth-ops',
          kind: 'module',
          label: 'Growth Ops',
          icon: 'TrendingUp',
          priority: 20,
          moduleId: 'growth-ops',
          route: { routeId: '/marketing-studio/growth' },
          tooltip: 'Optimización y escala',
        },
        {
          id: 'nav.advisor',
          kind: 'module',
          label: 'Advisor System',
          icon: 'Compass',
          priority: 30,
          moduleId: 'advisor-system',
          route: { routeId: '/marketing-studio/advisor' },
          tooltip: 'Recomendaciones inteligentes',
        },
      ],
    },
    {
      id: 'config',
      label: 'Gobernanza',
      priority: 100,
      collapsible: true,
      items: [
        {
          id: 'nav.governance',
          kind: 'module',
          label: 'Compliance',
          icon: 'ShieldCheck',
          priority: 10,
          moduleId: 'governance-compliance',
          route: { routeId: '/marketing-studio/governance' },
        },
        {
          id: 'nav.integrations',
          kind: 'module',
          label: 'Integrations',
          icon: 'Plug',
          priority: 20,
          moduleId: 'integrations-data',
          route: { routeId: '/marketing-studio/integrations' },
        },
        {
          id: 'nav.settings',
          kind: 'module',
          label: 'Suite Settings',
          icon: 'Settings2',
          priority: 30,
          moduleId: 'settings',
          route: { routeId: '/marketing-studio/settings' },
        },
      ],
    },
  ],
};
