-- 1. Refinar quant_market_history para usar Cents (BIGINT)
-- Esto garantiza precisión financiera absoluta y match con el contrato Zod.
ALTER TABLE public.quant_market_history 
    ALTER COLUMN open TYPE BIGINT USING (open * 100)::BIGINT,
    ALTER COLUMN high TYPE BIGINT USING (high * 100)::BIGINT,
    ALTER COLUMN low TYPE BIGINT USING (low * 100)::BIGINT,
    ALTER COLUMN close TYPE BIGINT USING (close * 100)::BIGINT;

-- 2. Crear tabla de Señales Desacopladas (Signal Engine Output)
CREATE TABLE IF NOT EXISTS public.quant_signals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL, -- Multi-tenancy
    bot_id UUID REFERENCES public.quant_bots(id) ON DELETE CASCADE,
    pair VARCHAR(20) NOT NULL,
    side VARCHAR(10) NOT NULL CHECK (side IN ('BUY', 'SELL', 'EXIT')),
    price BIGINT NOT NULL, -- In Cents
    environment trading_environment NOT NULL DEFAULT 'testnet',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'EXECUTED', 'REJECTED', 'EXPIRED')),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb, -- Audit data (RSI, SMA, Confidence)
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Habilitar RLS en Señales
ALTER TABLE public.quant_signals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only see signals from their bots" 
ON public.quant_signals FOR ALL 
USING (tenant_id = auth.uid() OR tenant_id = '00000000-0000-0000-0000-000000000000');

-- 4. Índices para el Gestor de Ejecución
CREATE INDEX IF NOT EXISTS idx_signals_pending 
ON public.quant_signals (status, created_at DESC) 
WHERE status = 'PENDING';

-- 5. Comentarios técnicos
COMMENT ON TABLE public.quant_signals IS 'Decoupled signals generated by the Signal Engine (Tier B). Consumed by Execution Manager (Tier C).';
COMMENT ON COLUMN public.quant_signals.price IS 'Price in Cents (e.g., 7042068 = $704.2068).';
