import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { HomeDataState } from '../../../data/home-data';
import { colors } from '../../../theme/colors';

type Tab = 'activity' | 'notifications' | 'organizations';
export function HomeScreen({ data, onNavigate }: { data: HomeDataState; onNavigate: (tab: Tab) => void }) {
  if (data.status === 'loading') return <Text style={styles.description}>Cargando resumen de plataforma...</Text>;
  if (data.status === 'error') return <Text style={styles.description}>No se pudo cargar el resumen. Inténtalo de nuevo.</Text>;
  const overview = data.overview;
  return <><Text style={styles.title}>Resumen de plataforma</Text><Text style={styles.description}>Supervisión global en un vistazo.</Text><View style={styles.statusCard}><Text style={styles.cardEyebrow}>ESTADO GENERAL</Text><Text style={styles.statusTitle}>{overview?.systemStatus === 'operational' ? 'Todo operativo' : 'Servicio degradado'}</Text><Text style={styles.cardDetail}>Última comprobación hace 2 min</Text></View><View style={styles.metricRow}><Metric label="Usuarios activos" value={overview?.activeUsers ?? 0} /><Metric label="Organizaciones" value={overview?.activeOrganizations ?? data.organizations.length} /><Metric label="Avisos" value={overview?.pendingNotifications ?? data.notifications.length} /></View><Text style={styles.sectionTitle}>Accesos rápidos</Text><View style={styles.quickLinks}><QuickLink label="Ver actividad" onPress={() => onNavigate('activity')} /><QuickLink label="Ver organizaciones" onPress={() => onNavigate('organizations')} /><QuickLink label="Ver notificaciones" onPress={() => onNavigate('notifications')} /></View></>;
}
function Metric({ label, value }: { label: string; value: number }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.cardDetail}>{label}</Text></View>; }
function QuickLink({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={styles.quickLink}><Text style={styles.quickLinkLabel}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ title: { color: colors.ink, fontSize: 28, fontWeight: '700' }, description: { color: colors.muted, fontSize: 16, lineHeight: 24, marginTop: 12 }, statusCard: { backgroundColor: colors.ink, borderRadius: 12, marginTop: 28, padding: 20 }, cardEyebrow: { color: colors.statusText, fontSize: 11, fontWeight: '700', letterSpacing: 1.2 }, statusTitle: { color: colors.white, fontSize: 22, fontWeight: '700', marginTop: 8 }, cardDetail: { color: colors.statusMuted, fontSize: 13, marginTop: 6 }, metricRow: { flexDirection: 'row', gap: 8, marginTop: 12 }, metric: { backgroundColor: colors.white, borderRadius: 10, flex: 1, padding: 12 }, metricValue: { color: colors.accent, fontSize: 24, fontWeight: '700' }, sectionTitle: { color: colors.ink, fontSize: 18, fontWeight: '700', marginTop: 28 }, quickLinks: { gap: 10, marginTop: 12 }, quickLink: { backgroundColor: colors.white, borderRadius: 8, justifyContent: 'center', minHeight: 48, paddingHorizontal: 16 }, quickLinkLabel: { color: colors.accent, fontSize: 15, fontWeight: '700' } });