import { z } from 'zod';
import { TradingEnvironmentSchema } from './market';

// ============= DOMAIN SCHEMAS =============

/**
 * @schema SignalMetadataSchema
 * @description Technical audit data for professional traders.
 */
export const SignalMetadataSchema = z.object({
  rsi_value: z.number().optional(),
  sma_value: z.number().optional(),
  atr_volatility: z.number().optional(),
  signal_confidence: z.number().min(0).max(100), // 0-100%
  logic_version: z.string(),
  indicators_snapshot: z.record(z.any()), // Raw indicators for audit
}).strict();

/**
 * @schema TradeSignalSchema
 * @description Decoupled signal event generated by the Signal Engine.
 */
export const TradeSignalSchema = z.object({
  id: z.string().uuid(),
  tenant_id: z.string().uuid(), // Required for multi-tenancy
  bot_id: z.string().uuid(),
  pair: z.string(),
  side: z.enum(['BUY', 'SELL', 'EXIT']),
  price: z.number().int().positive(), // In Cents
  environment: TradingEnvironmentSchema,
  metadata: SignalMetadataSchema,
  status: z.enum(['PENDING', 'EXECUTED', 'REJECTED', 'EXPIRED']),
  created_at: z.string().datetime(),
}).strict();

export type TradeSignal = z.infer<typeof TradeSignalSchema>;

// ============= ERROR CODES =============

export const SignalErrorCodesSchema = z.enum([
  'INSUFFICIENT_FUNDS',
  'RISK_LIMIT_EXCEEDED',
  'EXCHANGE_DISCONNECTED',
  'STRATEGY_MISMATCH',
]);

export type SignalErrorCode = z.infer<typeof SignalErrorCodesSchema>;
