import type { ReactNode } from 'react';
import type { ModuleConfig, SuiteConfig } from '@loopdev/contracts';
import type { NavMode, NavRouteRef } from '@loopdev/contracts';
import type { SuiteShellProps } from '../SuiteShell/types';
import type { SuiteCanvasProps } from '../../workspace/SuiteCanvas';
import type { SuiteSidebarContextualAction } from '../SuiteSidebar/types';

export type SuiteModuleRenderer = (module: ModuleConfig) => ReactNode;
export type SuiteModuleHeaderRenderer = (module: ModuleConfig) => ReactNode;
export type SuiteModuleToolbarRenderer = (module: ModuleConfig) => ReactNode;
export type SuiteModuleContextRenderer = (module: ModuleConfig) => ReactNode;
export type SuiteModuleContextFooterRenderer = (module: ModuleConfig) => ReactNode;
export type SuiteModuleContextPanelRenderer = (module: ModuleConfig) => ReactNode;
export type SuiteModuleContextPanelFooterRenderer = (module: ModuleConfig) => ReactNode;

export interface SuiteRuntimeProps {
  config: SuiteConfig;
  activeModuleId?: string;
  moduleRenderers?: Record<string, SuiteModuleRenderer>;
  moduleHeaderRenderers?: Record<string, SuiteModuleHeaderRenderer>;
  moduleToolbarRenderers?: Record<string, SuiteModuleToolbarRenderer>;
  moduleHeaderVisibility?: Partial<Record<string, boolean>>;
  moduleToolbarVisibility?: Partial<Record<string, boolean>>;
  moduleContextRenderers?: Record<string, SuiteModuleContextRenderer>;
  moduleContextFooterRenderers?: Record<string, SuiteModuleContextFooterRenderer>;
  moduleContextLabels?: Partial<Record<string, string>>;
  moduleContextVisibility?: Partial<Record<string, boolean>>;
  moduleContextShowFooter?: Partial<Record<string, boolean>>;
  moduleContextPanelRenderers?: Record<string, SuiteModuleContextPanelRenderer>;
  moduleContextPanelFooterRenderers?: Record<string, SuiteModuleContextPanelFooterRenderer>;
  moduleContextPanelLabels?: Partial<Record<string, string>>;
  moduleContextPanelVisibility?: Partial<Record<string, boolean>>;
  moduleContextPanelShowFooter?: Partial<Record<string, boolean>>;
  moduleContextPanelOnClose?: () => void;
  moduleContextSidebarCollapsed?: boolean;
  moduleContextSidebarShowCollapsedTrigger?: boolean;
  moduleContextSidebarMobileVisibility?: 'visible' | 'hidden';
  moduleContextSidebarOnCollapsedChange?: (collapsed: boolean) => void;
  children?: ReactNode;
  leftSlot: ReactNode;
  centerSlot: ReactNode;
  rightSlot: ReactNode;
  profileSlot?: ReactNode;
  mobileSidebarActions?: ReactNode;
  platformHeaderProps?: SuiteShellProps['platformHeaderProps'];
  onNavigate: (route: NavRouteRef) => void;
  contextualSidebarAction?: SuiteSidebarContextualAction | ReactNode | ((isRail: boolean) => ReactNode);
  onNavModeChange?: (mode: Exclude<NavMode, 'hidden'>) => void;
  appShellProps?: SuiteShellProps['appShellProps'];
  scrollResetKey?: string;
  canvasProps?: Omit<SuiteCanvasProps, 'children'>;
}
